Créer et éditer les identifier in uri
geovistory/ontome pull request #44
Opened 2023-09-15 12:45 UTC by perrauda

Resolves #19

2023-10-04 08:58 UTC, valamercery requested changes
Ne permettre la modification de l'URI d'une entité que si "No parameter" est sélectionné. Corriger également le problème vu en sprint pour le cas entity identifier.

2023-10-13 14:17 UTC, perrauda commented
Il faut ajouter les modifications en cascade quand on modifie l'identifier, comme indiqué dans l'issue

2023-10-20 12:53 UTC, valamercery approved these changes
Testé et approuvé

2023-11-21 14:42 UTC, dferhod requested changes
Review faite, tu peux créer la classe demandée en commentaire, tester et ça ira très bien :)

2023-11-21 14:42 UTC, dferhod commented on src/AppBundle/Entity/OntoClass.php
> +        function deleteAccents($str) {
Créer un dossier "Utils" dans "AppBundle".
Créer dedans une nouvelle classe StringSanitize.php
Cette classe contiendra la fonction deleteAccents($str) et potentiellement d'autres fonction de nettoyage et traitement de chaines de caractères

2023-11-21 14:42 UTC, dferhod commented on src/AppBundle/Entity/Property.php
> +        function deleteAccents($str) {
Utiliser la nouvelle fonction à créer dans la classe utilitaire StringSanitize mentionnée précédemment

2023-11-21 14:50 UTC, dferhod approved these changes
Ok !

2023-11-21 14:52 UTC, perrauda commented on src/AppBundle/Entity/OntoClass.php
> +        function deleteAccents($str) {
Done (StringUtils créé avant de lire ton commentaire)

2023-11-21 14:52 UTC, perrauda commented on src/AppBundle/Entity/Property.php
> +        function deleteAccents($str) {
Done (StringUtils créé avant de lire ton commentaire)

2023-11-21 14:52 UTC, merged