Import add identifier in uri
geovistory/ontome pull request #50
Opened 2023-09-15 13:03 UTC by perrauda

Resolves #49

2024-01-24 14:14 UTC, MPica approved these changes
All seems in order and to work as planned.

2024-02-05 15:28 UTC, dferhod requested changes
Voir commentaires, sinon c'est bon

2024-02-05 15:28 UTC, dferhod commented on src/AppBundle/Controller/ProjectController.php
> +                                        echo "- 2 scopes notes au moins ont la même langue. j".$newClassVersion->getClass()->getIdentifierInNamespace();
corriger le "j" qui traine

2024-02-05 15:28 UTC, dferhod commented on src/AppBundle/Controller/ProjectController.php
> +                                        echo "- 2 scopes notes au moins ont la même langue. j" . $newClassVersion->getClass()->getIdentifierInNamespace();
corriger le "j"

2024-02-06 10:43 UTC, merged